mqtt:
  sensor:
    - name: "Ventilation Temperature"
      unique_id: "ventilation_temperature"
      state_topic: "madelon/state/environment"
      unit_of_measurement: "°C"
      value_template: "{{ value_json.temperature }}"
      device_class: "temperature"
      device:
        identifiers: ["ventilation_system_01"]
        name: "Fresh Air System"
        model: "Fresh Air Ventilation"
        manufacturer: "Madelon"
      
    - name: "Ventilation Humidity"
      unique_id: "ventilation_humidity"
      state_topic: "madelon/state/environment"
      unit_of_measurement: "%"
      value_template: "{{ value_json.humidity }}"
      device_class: "humidity"
      device:
        identifiers: ["ventilation_system_01"]
        name: "Fresh Air System"
        model: "Fresh Air Ventilation"
        manufacturer: "Madelon"

  fan:
    - name: "Ventilation Fan"
      unique_id: "ventilation_fan"
      state_topic: "madelon/state/mode"
      command_topic: "madelon/ctrl/power"
      payload_on: "ON"
      payload_off: "OFF"
      state_value_template: >-
        {% if value == 'off' %}
          OFF
        {% else %}
          ON
        {% endif %}
      percentage_state_topic: "madelon/state/speed"
      percentage_command_topic: "madelon/ctrl/speed"
      percentage_value_template: >-
        {% if value == 'low' %}
          1
        {% elif value == 'medium' %}
          2
        {% elif value == 'high' %}
          3
        {% else %}
          0
        {% endif %}
      speed_range_min: 1
      speed_range_max: 3
      percentage_command_template: >-
        {% if value == 0 %}
          off
        {% elif value == 1 %}
          low
        {% elif value == 2 %}
          medium
        {% elif value == 3 %}
          high
        {% endif %}
      device:
        identifiers: ["ventilation_system_01"]
        name: "Fresh Air System"
        model: "Fresh Air Ventilation"
        manufacturer: "Madelon"

input_select:
  ventilation_mode:
    name: "Ventilation Mode"
    options:
      - "Manual"
      - "Auto"
      - "Timer"
      - "Manual + Bypass"
      - "Auto + Bypass"
      - "Timer + Bypass"
    initial: "Manual"

automation:
  - alias: "Ventilation Mode Control"
    description: "将模式选择器的改变转换为MQTT控制命令"
    trigger:
      platform: state
      entity_id: input_select.ventilation_mode
    action:
      - service: mqtt.publish
        data_template:
          topic: "madelon/ctrl/mode"
          payload: >-
            {% set mode = trigger.to_state.state | lower %}
            {% if mode == 'manual' %}manual
            {% elif mode == 'auto' %}auto
            {% elif mode == 'timer' %}timer
            {% elif mode == 'manual + bypass' %}manual_bypass
            {% elif mode == 'auto + bypass' %}auto_bypass
            {% elif mode == 'timer + bypass' %}timer_bypass
            {% endif %}

  - alias: "Ventilation Mode Sync"
    description: "同步设备状态到模式选择器"
    trigger:
      platform: mqtt
      topic: "madelon/state/mode"
    action:
      - service: input_select.select_option
        target:
          entity_id: input_select.ventilation_mode
        data_template:
          option: >-
            {% set mode = trigger.payload %}
            {% if mode == 'manual' %}Manual
            {% elif mode == 'auto' %}Auto
            {% elif mode == 'timer' %}Timer
            {% elif mode == 'manual_bypass' %}Manual + Bypass
            {% elif mode == 'auto_bypass' %}Auto + Bypass
            {% elif mode == 'timer_bypass' %}Timer + Bypass
            {% endif %}



# 为新风系统创建单独的 HomeKit 实例
homekit:
  - name: Fresh Air System
    port: 51828  # 使用不同于默认的端口
    filter:
      include_entities:
        - fan.ventilation_fan
        - input_select.ventilation_mode
        - sensor.ventilation_temperature
        - sensor.ventilation_humidity
    entity_config:
      fan.ventilation_fan:
        name: "Fresh Air System"
      input_select.ventilation_mode:
        name: "Operation Mode"
      sensor.ventilation_temperature:
        name: "Fresh Air Temperature"
      sensor.ventilation_humidity:
        name: "Fresh Air Humidity"

